# Data Processing

## Data cleaning

In [1]:
import pandas as pd
import numpy as np
import openpyxl

In [80]:
df = pd.read_excel("Online Retail.xlsx")
#Display the first 5 rows of the data.
print(df.shape)
df.head()

(541909, 8)

,InvoiceNo,StockCode,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country
0,536365,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2010-12-01 08:26:00,2.55,17850.0,United Kingdom
1,536365,71053,WHITE METAL LANTERN,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
2,536365,84406B,CREAM CUPID HEARTS COAT HANGER,8,2010-12-01 08:26:00,2.75,17850.0,United Kingdom
3,536365,84029G,KNITTED UNION FLAG HOT WATER BOTTLE,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom
4,536365,84029E,RED WOOLLY HOTTIE WHITE HEART.,6,2010-12-01 08:26:00,3.39,17850.0,United Kingdom

In [81]:
# 数据类型和缺失值
df.info()

# 描述统计
df.describe()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 541909 entries, 0 to 541908
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   InvoiceNo    541909 non-null  object
 1   StockCode    541909 non-null  object
 2   Description  540455 non-null  object
 3   Quantity     541909 non-null  int64
 4   InvoiceDate  541909 non-null  datetime64[ns]
 5   UnitPrice    541909 non-null  float64
 6   CustomerID   406829 non-null  float64
 7   Country      541909 non-null  object
dtypes: datetime64[ns](1), float64(2), int64(1), object(4)
memory usage: 33.1+ MB

,Quantity,InvoiceDate,UnitPrice,CustomerID
count,541909.000000,541909,541909.000000,406829.000000
mean,9.552250,2011-07-04 13:34:57.156386048,4.611114,15287.690570
min,-80995.000000,2010-12-01 08:26:00,-11062.060000,12346.000000
25%,1.000000,2011-03-28 11:34:00,1.250000,13953.000000
50%,3.000000,2011-07-19 17:17:00,2.080000,15152.000000
75%,10.000000,2011-10-19 11:27:00,4.130000,16791.000000
max,80995.000000,2011-12-09 12:50:00,38970.000000,18287.000000
std,218.081158,NaN,96.759853,1713.600303

### processing missing values

In [82]:
#Filter out the rows that do not have a customer ID, and retain only the data with valid customer IDs.
df = df[~df["CustomerID"].isna()].copy()
df["CustomerID"] = df["CustomerID"].astype(int).astype(str)

In [83]:
# return orders
df["IsReturn"] = df["Quantity"] < 0

In [84]:
# only save normal purchase order
df = df[
    (df["Quantity"] > 0) &
    (df["UnitPrice"] > 0)
].copy()

In [85]:
# time field
df["InvoiceDate"] = pd.to_datetime(df["InvoiceDate"])

# time features-data-month-week
df["Date"] = df["InvoiceDate"].dt.date
df["YearMonth"] = df["InvoiceDate"].dt.to_period("M")
df["Week"] = df["InvoiceDate"].dt.isocalendar().week
df["DayOfWeek"] = df["InvoiceDate"].dt.dayofweek
df["IsWeekend"] = df["DayOfWeek"].isin([5, 6]).astype(int)

df["Hour"] = df["InvoiceDate"].dt.hour

In [118]:
df_clean = df.copy()